function [fitresult, gof] = createFitTombe(tx, ty)
%CREATEFIT(TX,TY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tx
%      Y Output: ty
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Apr-2021 21:45:48


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tx, ty );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 4.7527626432123e-05;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
plot( fitresult, xData, yData );
% Label axes
xlabel tx
ylabel ty
grid off


